services:
  server:
   restart: always
   build:
    context: .
    dockerfile: Dockerfile
   ports:
    - 8080:8080
   depends_on:
    - db
   environment:
    - SERVER_PORT = 8080
    - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/jesus

  db:
    image: postgres:15-alpine
    restart: always
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jesus
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.utf8"
    ports:
      - "5438:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local

networks:
  web:
   name: web
   external: true